

export const FRIEND_LOAD = 'FRIEND_LOAD';
export const FRIEND_REQUEST_SUCCESS = 'FRIEND_REQUEST_SUCCESS';
export const FRIEND_REQUEST_FAIL = 'FRIEND_REQUEST_FAIL';
export const GET_FRIEND_REQUESTS = 'GET_FRIEND_REQUESTS';
export const FRIEND_RESPONSE_SUCCESS = 'FRIEND_RESPONSE_SUCCESS';
export const FRIEND_RESPONSE_FAIL = 'FRIEND_RESPONSE_FAIL';
